# Generated by Django 6.0.3 on 2026-04-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='max_appointments',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='shift',
        ),
    ]
