# Generated by Django 6.0.3 on 2026-04-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
